name: Build OpenWrt images

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v3.5.3

            - name: Build images in container
              run: |
                docker run --name builder \
                  -u $(id -u) -e USER=$(id -u) \
                  -v $(pwd)/:$(pwd)/ -w $(pwd) \
                  ghcr.io/ivc/openwrt-bazel:v1.0 \
                  bazel --output_user_root=$(pwd)/output \
                  build //:rpi4_docker

            - run: mv bazel-bin/*.gz .

            - name: Upload RPi4 ext4 image
              uses: actions/upload-artifact@v3.1.2
              with:
                name: rpi4_docker-root.ext4.gz
                path: rpi4_docker-root.ext4.gz

            - name: Upload RPi4 squashfs image
              uses: actions/upload-artifact@v3.1.2
              with:
                name: rpi4_docker-root.squashfs.gz
                path: rpi4_docker-root.squashfs.gz
